### ISSUE TITLE
Edge debugger getting HTTP error 400

### ISSUE THREAD

**Issue by purelight01** [Microsoft/vscode-edge-debug#18]
I can't seem to make the edge debugging from vs code working.
I tried both the attach and launch debug, nothing worked.
(Fyi, the chrome debugging worked just fine)

I am using the windows 10 preview build - fast ring.
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

Here is the error log:

    at ClientRequest.response (C:\Users\ahalim\.vscode\extensions\msjsdiag.debugger-for-edge-0.4.1\node_modules\ws\lib\WebSocket.js:694:15)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)

[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:34] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:35] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:35] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:35] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:35] [error] Handshake ended with HTTP error: 400
[2017-10-10 16:43:35] [error] Handshake ended with HTTP error: 400

**Comment by riverar** [comment]
@auchenberg Hello?
