### ISSUE TITLE
Can't debug in Windows 10

### ISSUE THREAD

**Issue by sandhilt** [Microsoft/vscode-edge-debug#22]
My specs are:
Windows 10.0.16299.334
Microsoft Edge 41.16299.334.0
Microsoft EdgeHTML 16.16299

VSCode 1.21.1
Debugger for Edge 0.4.1

Project using:
NodeJS 8.11.1
[create-react-app](https://github.com/facebook/create-react-app) v1.1.4

```log
  ›OS: win32 x64
  ›Node version: v7.9.0
  ›Adapter version: 0.0.5
  ›initialize({"clientID":"vscode","adapterID":"edge","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"pt-br"})
  ›attach({"name":"Launch localhost with sourcemaps","type":"edge","request":"launch","url":"http://localhost:3000/","sourceMaps":true,"webRoot":"C:\\Users\\Bruno\\Documents\\Projetos\\my-app/src","diagnosticLogging":true,"__sessionId":"5e10172c-a627-4fd7-b6d8-a66e3f909a7f","port":9222})
  ›Attempting to attach on port 9222
  ›Error: unexpected server response (400)
    at ClientRequest.response (C:\Users\Bruno\.vscode\extensions\msjsdiag.debugger-for-edge-0.4.1\node_modules\ws\lib\WebSocket.js:694:15)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"[debugger-for-chrome] unexpected server response (400)"}
  ›******** ERROR! Unhandled promise rejection: Error: unexpected server response (400)
  ›From client: disconnect({"restart":false})
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

How to reproduce:
1- With NodeJS installed, run in cmd (or poweshell): `npx create-react-app my-app`
2- With VSCode and [extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge) installed, create this `launch.json` in `.vscode` folder with this content:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch localhost with sourcemaps",
            "type": "edge",
            "request": "launch",
            "url": "http://localhost:3000/",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/src",
            "diagnosticLogging": true,
        }
    ]
}
```
3- In root folder (`my-app`), run this command: `npm start` and close tab of Edge in startup.
4- Finally, try run debugger and this happen.

**Comment by dhanvikapila** [comment]
This repository is deprecated and no longer maintained.  Active development has been happening on the newer Edge debugging extension at [Microsoft/vscode-edge-debug2](https://github.com/Microsoft/vscode-edge-debug2)
